# Permalinks
permalink:           pretty

# Setup
title:               aiman alghamdi
tagline:             Data Science Blog
url:                 https://aiman2019.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              aiman2019
  url:               
  email:             aiman.m.alghamdi@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/aiman2019

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
